services:
  airflow-scheduler:
    image: apache/airflow:2.2.2
    container_name: airflow-scheduler
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW_USER=airflow
      - AIRFLOW_PASSWORD=airflow
      - AIRFLOW_DB_HOST=postgres
      - AIRFLOW_DB_PORT=5432
      - AIRFLOW_DB_USER=airflow
      - AIRFLOW_DB_PASSWORD=airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres

  airflow-webserver:
    image: apache/airflow:2.2.2
    container_name: airflow-webserver
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW_USER=airflow
      - AIRFLOW_PASSWORD=airflow
      - AIRFLOW_DB_HOST=postgres
      - AIRFLOW_DB_PORT=5432
      - AIRFLOW_DB_USER=airflow
      - AIRFLOW_DB_PASSWORD=airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres
      - airflow-scheduler

  postgres:
    image: postgres:13.4
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - ./postgres-data:/var/lib/postgresql/data