version: '3.9'

volumes:
  db: 
    driver: local
    driver_opts:
      type: none
      device: /mnt/st1/docker/postgres_docker
      o: bind


services:
  db:
    image: postgres:15.3-bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB  = personal
      - PGDATA = /tmp
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/data/

