version: '3.8'
services:
  db:
    image: postgres:15.3-bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB  = personal
      - PGDATA = /tmp
    ports:
      - '5434:5432'
    volumes:
      - /mnt/data extra/database_docker:/var/lib/postgresql/data/
      - ./backend/data/config.sql:/docker-entrypoint-initdb.d/config.sql
volumes:
  db:
