version: '3.7'

services:
  spark-master:
    image: bitnami/spark:latest

    command: bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      # - SPARK_MASTER_MEMORY=6g
      # - SPARK_DAEMON_MEMORY=6g
      - SPARK_LOCAL_IP=spark-master
      # - SPARK_DAEMON_JAVA_OPTS="-Dx=y"
      # - SPARK_DRIVER_BIND_ADDRESS=0.0.0.0
      # - SPARK_DRIVER_PORT=5000
      # - SPARK_MASTER_LOG /path/to/spark-master-logs
    ports:
      - "9090:8080"
      - "7077:7077"
    # expose:
    #   - "5000"
    #   - "7077"
    volumes:
      - /mnt/data extra/apps:/opt/spark-apps
      - /mnt/data extra/data:/opt/spark-data
      - /mnt/st1/JAR/postgresql-42.5.1.jar:/opt/bitnami/spark/jars/postgresql-42.5.1.jar
    networks:
      - my-network

  spark-worker-1:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 #--webui-port 8081

    depends_on:
      - spark-master
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 7
      SPARK_WORKER_MEMORY: 12g
      SPARK_EXECUTOR_MEMORY: 12g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      PARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
    ports:
      - "8881:8881"
      - "8081:8081"
    volumes:
      - /mnt/data extra/apps:/opt/spark-apps
      - /mnt/data extra/data:/opt/spark-data
      - /mnt/st1/JAR/postgresql-42.5.1.jar:/opt/bitnami/spark/jars/postgresql-42.5.1.jar
    networks:
      - my-network

  spark-worker-2:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 #--webui-port 8082
    depends_on:
      - spark-master
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 7
      SPARK_WORKER_MEMORY: 12g
      SPARK_EXECUTOR_MEMORY: 12g
      SPARK_WORKER_PORT: 8882
      SPARK_WORKER_WEBUI_PORT: 8082
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      PARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
    ports:
      - "8882:8882"
      - "8082:8082"

    volumes:
      - /mnt/data extra/apps:/opt/spark-apps
      - /mnt/data extra/data:/opt/spark-data
      - /mnt/st1/JAR/postgresql-42.5.1.jar:/opt/bitnami/spark/jars/postgresql-42.5.1.jar
    networks:
      - my-network


networks:
  my-network:
    external: true

volumes:
  db:
